package main

import "log/slog"

func Seed(st *Store) error {
	author, err := st.UpsertUser("seed-author", "registry@openbotkit.dev", "OpenBotKit Team", "")
	if err != nil {
		return err
	}

	seeds := []UseCase{
		// ── Customer Support ──────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Automated Ticket Triage and Routing",
			Description:       "AI classifies incoming support tickets by intent, urgency, sentiment, and product area, then routes them to the correct team. Zendesk reports AI-powered triage achieves 90%+ accuracy, reducing first-response time by 30%. Unity Technologies cut 8,000 tickets/month after implementing AI triage. Eliminates the 'wrong queue' problem that plagues high-volume support orgs.",
			Domain:            "Customer Support",
			IndustryTags:      "SaaS,E-commerce,Fintech,Telecom",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "Systematic misrouting causes delays and customer frustration but no data loss. Worst case is a temporary spike in resolution time.",
			SafetyOversight:   "Agents see every ticket and can re-route. Supervisors monitor accuracy dashboards. Low-confidence classifications get flagged for manual review.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "AI-Assisted Agent Response Suggestions",
			Description:       "AI monitors live conversations and suggests draft responses, relevant knowledge base articles, and next-best-actions in real time. Agents review, edit, and send. Klarna's AI assistant handles the equivalent work of 700 agents, resolving issues in 2 minutes vs. 11 minutes previously. Contributed to a projected $40M profit improvement in 2024.",
			Domain:            "Customer Support",
			IndustryTags:      "SaaS,Insurance,Banking,E-commerce",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "An agent sending an incorrect AI suggestion (wrong refund amount, incorrect policy) could cause financial loss for one customer per interaction.",
			SafetyOversight:   "Agent is the human-in-the-loop for every message. QA teams audit conversations. AI-suggested responses sent without edits are flagged for review.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "RAG-Based Customer Self-Service Bot",
			Description:       "AI answers customer questions by retrieving content from the knowledge base, docs, and past tickets, then generating grounded natural-language responses. Unlike keyword-matching FAQ bots, RAG systems understand intent and synthesize answers from multiple sources. Intercom Fin resolves up to 50% of queries without human involvement. Wistia saw a 75% decrease in first-response time.",
			Domain:            "Customer Support",
			IndustryTags:      "SaaS,E-commerce,Fintech,EdTech",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "A hallucinated answer at scale (e.g., consistently misquoting refund policy) could affect thousands of customers. Financial and brand damage are the primary risks.",
			SafetyOversight:   "Confidence thresholds escalate to humans when low. Companies start with narrow scope and expand gradually. Phased rollouts send to a small group first.",
			AuthorID:          author.ID,
		},

		// ── Finance ──────────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Automated Invoice Processing and AP Automation",
			Description:       "AI extracts data from invoices (PDF, scans, emails) using OCR and NLP, matches against purchase orders, flags discrepancies, and routes for approval. Siemens achieved 83% straight-through processing across 300+ entities with Basware. Organizations report 70-80% reduction in manual data entry. Cost-per-invoice drops from $15-40 (manual) to $2-5.",
			Domain:            "Finance",
			IndustryTags:      "Financial Services,Manufacturing,Retail,Healthcare",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "Worst case is a duplicate or incorrect payment, mitigated by duplicate detection and approval workflows. Individual errors bounded by payment approval limits.",
			SafetyOversight:   "Exception queues surface low-confidence extractions. Approval hierarchies based on dollar thresholds. Daily reconciliation reports flag anomalies.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "AI-Powered Transaction Fraud Detection",
			Description:       "ML models analyze transaction patterns in real time, scoring each transaction for fraud probability using hundreds of behavioral signals. JPMorgan's AI reduced false positives by 50% while catching 20% more actual fraud. Mastercard's Decision Intelligence reduced false declines by 50%, recovering billions in legitimate transactions. Feedzai customers see 60% fraud loss reduction in year one.",
			Domain:            "Finance",
			IndustryTags:      "Banking,Payment Processing,Insurance,E-commerce,Fintech",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "False negatives let fraud through. False positives block legitimate customers, causing revenue loss and churn. Both are bounded by transaction limits and escalation rules.",
			SafetyOversight:   "Fraud analysts review flagged transactions. Model performance dashboards track precision/recall daily. Regulatory requirements mandate human review for SARs.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "Intelligent Cash Flow Forecasting",
			Description:       "AI predicts future cash positions by analyzing historical flows, AR aging, AP schedules, seasonal patterns, and economic indicators. Forecast accuracy improves from 60-70% (manual) to 85-95% (AI-assisted) at 13-week horizons. HighRadius customers achieve 90%+ accuracy, reducing idle cash by 30-50%. For a company with $100M in cash, 1% better yield on freed-up idle cash is $1M annually.",
			Domain:            "Finance",
			IndustryTags:      "Corporate Treasury,Manufacturing,Retail,SaaS",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         false,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "Wrong forecast could cause a cash shortfall (emergency borrowing) or excess idle cash (opportunity cost). Both are recoverable within days.",
			SafetyOversight:   "Treasury analysts review AI forecasts against their judgment. Variance reports compare predictions to actuals weekly. Critical decisions always require human approval.",
			AuthorID:          author.ID,
		},

		// ── Sales ────────────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Predictive Lead Scoring and Prioritization",
			Description:       "ML models analyze CRM data, behavioral signals (email opens, page visits), and firmographic data to score leads by conversion likelihood. Reps focus on highest-scoring leads instead of working lists sequentially. 6sense customers report 3x pipeline growth. Salesforce research shows high-performing teams are 1.5x more likely to use AI lead scoring.",
			Domain:            "Sales",
			IndustryTags:      "B2B SaaS,Financial Services,Professional Services,Manufacturing",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "A bad model means reps spend time on lower-quality leads, but no customer-facing damage occurs. No automated outreach is triggered.",
			SafetyOversight:   "Sales managers review conversion rates by score bucket weekly. Models retrained on actual outcomes. Reps can override scores based on judgment.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "Conversational AI for Inbound Lead Qualification",
			Description:       "AI chatbots handle inbound qualification on websites: answering visitor questions, gathering BANT data (budget, authority, need, timeline), and booking meetings for reps. Enables sub-second response vs. 30+ minutes average. Drift/Salesloft customers report 20% qualified pipeline increase. MongoDB attributed 70% of qualified pipeline to conversational AI.",
			Domain:            "Sales",
			IndustryTags:      "B2B SaaS,Professional Services,Real Estate,Financial Services",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "A malfunctioning bot could give incorrect pricing, make unauthorized promises, or offend prospects. As the first touchpoint, it directly impacts brand perception and pipeline.",
			SafetyOversight:   "Conversation transcripts logged and reviewed. Escalation rules route complex prospects to humans. Strict guardrails on pricing and commitment topics.",
			AuthorID:          author.ID,
		},

		// ── Marketing ────────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Dynamic Email Personalization and Send-Time Optimization",
			Description:       "AI personalizes email subject lines, body content, and send times per recipient at scale. Instead of A/B testing two variants, the system generates dozens of variants per recipient. eBay's AI-generated subjects outperformed human-written by 15.8% in open rates across millions of emails. Phrasee delivered 2x click rate improvement for Virgin Holidays.",
			Domain:            "Marketing",
			IndustryTags:      "E-commerce,Retail,B2B SaaS,Travel,Media",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "A poorly generated subject line or body could reach millions of recipients before detection. Reputational damage is the primary risk. Mitigated by phased rollouts.",
			SafetyOversight:   "Marketing teams approve content templates and brand guardrails. Automated alerts flag engagement drops. Staged rollouts: 5% first, measure, then expand.",
			AuthorID:          author.ID,
		},

		// ── HR ───────────────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "AI Resume Screening and Candidate Shortlisting",
			Description:       "NLP models scan resumes, extract structured data (skills, experience, education), and rank candidates against job requirements. Unilever reported 75% reduction in time-to-hire and $1M+ annual recruiting cost savings with HireVue AI across 15 countries. Critical to audit for bias: Amazon scrapped an internal tool in 2018 after it penalized resumes containing 'women's.'",
			Domain:            "HR",
			IndustryTags:      "Consumer Goods,Financial Services,Technology,Retail,Healthcare",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "Qualified candidates silently rejected at scale. If the model has systematic bias, an entire demographic could be screened out. Legal exposure under EEOC and AI hiring laws (NYC Local Law 144).",
			SafetyOversight:   "Recruiters review shortlisted candidates. Periodic bias audits across protected categories. NYC requires annual bias audits. Candidate appeal process recommended.",
			AuthorID:          author.ID,
		},

		// ── Productivity ─────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "AI Meeting Summarization and Action Item Tracking",
			Description:       "AI joins virtual meetings, transcribes in real time, generates structured summaries, and extracts action items with owners and deadlines. Otter.ai reports 4 hours saved per knowledge worker per week. Microsoft Copilot has 1M+ paying customers, with 70% reporting increased productivity. For a 100-person team at $75/hr, 4 recovered hours/week is $1.56M annually.",
			Domain:            "Productivity",
			IndustryTags:      "Technology,Consulting,Financial Services,Legal",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "A leaked or misrouted transcript could expose M&A discussions, HR matters, or client data. Risk is data exposure, not incorrect action.",
			SafetyOversight:   "Participants review summaries before distribution. Admins control which meetings are recorded. Retention policies and access controls on transcript storage.",
			AuthorID:          author.ID,
		},

		// ── Legal ────────────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Contract Review with Clause-Level Risk Scoring",
			Description:       "AI analyzes contracts (NDAs, MSAs, vendor agreements) to extract clauses, flag deviations from standard terms, and assign risk scores. Compares against a company's approved playbook, highlights non-standard language, and suggests redlines. LawGeex's peer-reviewed study: AI achieved 94% accuracy on NDA review vs. 85% for experienced lawyers, in 26 seconds vs. 92 minutes. JP Morgan's COiN saves 360,000 hours/year.",
			Domain:            "Legal",
			IndustryTags:      "Corporate Legal,Financial Services,Technology,Insurance",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "A missed liability cap or indemnification clause could expose a company to uncapped financial risk on a single deal. Systemic risk is limited since each contract is individually executed.",
			SafetyOversight:   "Lawyer reviews every flagged contract before signature. Low-confidence items escalated to senior counsel. Confidence scores provided per clause.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "AI-Powered Legal Research and Case Discovery",
			Description:       "Attorneys query case law and regulations using natural language instead of Boolean search. AI surfaces relevant precedents and predicts likely outcomes from historical data. Attorneys complete research 25-40% faster with higher recall. Allen & Overy deployed CoCounsel firm-wide with 30-40% research time reduction. Legal research is 30-50% of associate billable hours, making efficiency gains directly impactful.",
			Domain:            "Legal",
			IndustryTags:      "Litigation,Corporate Law,Government,Insurance,IP",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         false,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "Worst case is citing a non-existent or overturned case, which could result in court sanctions and malpractice exposure. Well-understood risk with clear mitigation.",
			SafetyOversight:   "Attorneys validate every citation against source databases. Shepardizing (case validity checking) remains mandatory. Direct links to verified case text provided.",
			AuthorID:          author.ID,
		},

		// ── Healthcare ───────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Radiology AI for Breast Cancer Screening",
			Description:       "Deep learning models analyze mammograms alongside radiologists to detect early-stage breast cancer. A 2023 Lancet Oncology trial across 80,000 women in Sweden found AI-assisted screening detected 20% more cancers while cutting radiologist workload by 44%. Lunit INSIGHT is FDA-cleared and deployed in 4,000+ institutions across 50+ countries with 96%+ sensitivity.",
			Domain:            "Healthcare",
			IndustryTags:      "Radiology,Oncology,Hospital Systems,Health Insurance",
			RiskLevel:         "high",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "A false negative is a missed cancer. A faulty model in a screening program could affect thousands before detection. Regulated by FDA/CE marking with clinical validation protocols.",
			SafetyOversight:   "Radiologists review every AI-flagged image. Performance metrics monitored against clinical benchmarks. Regulatory bodies require periodic revalidation.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "Ambient AI Scribe for Clinical Documentation",
			Description:       "AI listens to physician-patient conversations and generates structured clinical notes (SOAP notes, visit summaries) in the EHR. Eliminates the 2+ hours/day physicians spend on documentation. Nuance DAX Copilot saves 7 minutes per encounter with 70% reduction in burnout. Deployed across The Permanente Medical Group (8,000+ physicians). 85% of notes need minimal or no edits.",
			Domain:            "Healthcare",
			IndustryTags:      "Primary Care,Specialty Medicine,Hospital Systems,Telehealth",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         true,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "An inaccurate note (wrong medication dosage, incorrect allergy) signed without review could cause a treatment error. Risk is bounded to individual encounters.",
			SafetyOversight:   "Physicians review, edit, and sign every note. Low-confidence sections highlighted. EHR audit trails track all edits. Health systems conduct periodic accuracy audits.",
			AuthorID:          author.ID,
		},

		// ── Engineering ──────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "AI Code Review with Security Vulnerability Detection",
			Description:       "AI analyzes every pull request for code quality, security vulnerabilities (SQL injection, XSS, secrets in code), and coding standards before human reviewers see the code. GitHub Copilot catches issues in 60%+ of PRs and reduces review time by 30%. Google's internal AI review tool covers the majority of code changes, with developers accepting suggestions 40% of the time on first pass.",
			Domain:            "Engineering",
			IndustryTags:      "Software Development,Cloud Infrastructure,Fintech,Cybersecurity,SaaS",
			RiskLevel:         "low",
			ROIPotential:      "medium",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         false,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "Worst case is a missed vulnerability that human reviewers also miss. Bounded by downstream testing, staging, and monitoring. IBM estimates bugs in production cost 6x more to fix than those caught in review.",
			SafetyOversight:   "Developers review all suggestions. CI/CD pipelines run independently. Code owners must approve merges. AI is additive to existing review processes.",
			AuthorID:          author.ID,
		},
		{
			ID:                newID(),
			Title:             "AIOps: Predictive Incident Detection and Automated Remediation",
			Description:       "AI monitors production telemetry (logs, metrics, traces) to detect anomalies before they become incidents, correlates alerts to find root cause, and executes pre-approved runbooks for known patterns. PagerDuty reduces alert noise by 70-80% and MTTA by 40%. LinkedIn cut MTTR by 30% and false alerts by 60%. Gartner estimates average IT downtime at $5,600/minute.",
			Domain:            "Engineering",
			IndustryTags:      "Cloud Infrastructure,SaaS,E-Commerce,Financial Services,Telecom",
			RiskLevel:         "medium",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         false,
			SafetyAutonomous:  true,
			SafetyBlastRadius: "Incorrect automated remediation could worsen an outage (e.g., restarting a healthy service). Bounded by safety limits: max scale-down %, one-at-a-time restarts, automatic rollback triggers.",
			SafetyOversight:   "Engineers define approved runbooks and safety boundaries. Novel incidents escalate to humans. Graduated trust model: observe-only first, then low-risk automation, then broader scope.",
			AuthorID:          author.ID,
		},

		// ── Operations ───────────────────────────────────────────────
		{
			ID:                newID(),
			Title:             "Intelligent Document Processing for Procurement",
			Description:       "AI extracts structured data from unstructured documents (invoices, POs, receipts, contracts) using OCR combined with transformer models. Matches invoices to POs, flags discrepancies, routes approvals. JP Morgan's COiN processes 12,000 credit agreements/year in seconds, work that took 360,000 hours of human review. Deloitte found 73% of shared services orgs use or pilot IDP in AP.",
			Domain:            "Operations",
			IndustryTags:      "Financial Services,Manufacturing,Logistics,Government",
			RiskLevel:         "low",
			ROIPotential:      "high",
			Status:            "published",
			ImplStatus:        "production",
			Visibility:        "public",
			SafetyPII:         false,
			SafetyAutonomous:  false,
			SafetyBlastRadius: "Mismatched invoice-to-PO could lead to incorrect payment, caught by existing financial controls (three-way matching, approval thresholds). Worst case is a delayed payment.",
			SafetyOversight:   "AP clerks review exceptions. Finance managers approve above thresholds. Standard financial controls (segregation of duties, audit trails) remain in place.",
			AuthorID:          author.ID,
		},
	}

	for i := range seeds {
		seeds[i].Slug = slugify(seeds[i].Title) + "-" + seeds[i].ID[:8]
		if err := st.CreateUseCase(&seeds[i]); err != nil {
			slog.Warn("seed: skip existing", "title", seeds[i].Title, "error", err)
			continue
		}
		slog.Info("seed: created", "title", seeds[i].Title)
	}

	return nil
}
